### ISSUE TITLE
Not able to initialize Engine on Android.

### ISSUE THREAD

**Issue by Ajay-Jadhao** [maxant/rules#3]
Hi @maxant 

`java.lang.ExceptionInInitializerError
                                                                 at org.mvel2.MVEL.compileExpression(MVEL.java:810)
                                                                 at org.mvel2.MVEL.compileExpression(MVEL.java:820)
                                                                 at org.mvel2.MVEL.compileExpression(MVEL.java:723)
                                                                 at ch.maxant.rules.Engine$CompiledRule.<init>(Engine.java:385)
                                                                 at ch.maxant.rules.Engine$CompiledRule.<init>(Engine.java:380)
                                                                 at ch.maxant.rules.Engine.init(Engine.java:204)
                                                                 at ch.maxant.rules.Engine.<init>(Engine.java:114)`

**Comment by maxant** [comment]
Hi, sorry, I only saw this just now. I suspect it is related to the "rule" i.e. the mvel expression you are putting into the rule engine. Did you manage to solve this problem on your own?
